import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {parseCSV,inspectData} from '../dist/assets/analytics.mjs';
import {effect,economics,allocationCheck,samplePlan} from '../dist/assets/investigation.mjs';
import {caseFile} from '../dist/assets/case-source.mjs';
const bytes=fs.readFileSync('data/private/'+caseFile.filename),hash=createHash('sha256').update(bytes).digest('hex');
if(hash!==caseFile.sha256||bytes.length!==caseFile.bytes)throw Error('Source file does not match the pinned manifest.');
const summary=inspectData(parseCSV(bytes.toString('utf8'))),e=effect(summary);
const output={file:caseFile,hash,summary,effect:e,economics:economics(summary),allocation:allocationCheck(summary),method:'Newcombe / Wilson 95%; independent binomial users; economic intervals conditional on case CPM and margin'};
fs.writeFileSync('data/private/rocket-inspection.json',JSON.stringify(output,null,2));console.log(JSON.stringify({hash,audit:summary.audit,arms:summary.arms,total:summary.all,effect:e,economics:output.economics,allocation:output.allocation},null,2));
